### ISSUE TITLE
Unable to find image 'unityci/editor:ubuntu-2020.3.26f1-linux-il2cpp-1'

### ISSUE THREAD

**Issue by yong2khoo88** [yanniboi/RogueCI#2]
Hi, thanks for your samples. 
However, when i try build for **Android**, i am hitting the error as stated:
`Unable to find image 'unityci/editor:ubuntu-2020.3.26f1-linux-il2cpp-1'`

below shows the yaml:
```
name: Actions 😎

on: [push]

jobs:
  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
          
      # Cache
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
      # Test
      - name: Run tests
        uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          
     # Build
      - name: Build project
        uses: game-ci/unity-builder@v2
        with:
          targetPlatform: Android
```
